//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class lec_module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lec_module()
        {
            this.stu_module = new HashSet<stu_module>();
        }
    
        public int id { get; set; }
        public int lecturer { get; set; }
        public int module { get; set; }
        public int degree { get; set; }
        public int intake { get; set; }
    
        public virtual degree degree1 { get; set; }
        public virtual intake intake1 { get; set; }
        public virtual module module1 { get; set; }
        public virtual lecturer lecturer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stu_module> stu_module { get; set; }
        [NotMapped]
        public string moduleName { get; set; }
    }
}
