//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_module
    {
        public int id { get; set; }
        public int student { get; set; }
        public int module { get; set; }
        public int mark { get; set; }
    
        public virtual lec_module lec_module { get; set; }
        public virtual student student1 { get; set; }
    }
}
