//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class student_dataEntities2 : DbContext
    {
        public student_dataEntities2()
            : base("name=student_dataEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<degree> degrees { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<intake> intakes { get; set; }
        public virtual DbSet<lec_module> lec_module { get; set; }
        public virtual DbSet<lecturer> lecturers { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<stu_module> stu_module { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
